version: "3.9"
services:
  media:
    build: .
    ports:
      - "8000:8000"
    environment:
      REPO_DIR: /repo
      QUARANTINE_DIR: /repo_quarantine
      SHOW_MEDIA_DIR: /repo_show
      CONFIG_DIR: /config
      GOOGLE_SERVICE_ACCOUNT_JSON: /config/google-service-account.json
      GOOGLE_SHEET_NAME: Media Repo Inventory
    volumes:
      - /Users/jspodick/Documents/Video/TestFolder:/repo:rw
      - /Users/jspodick/Documents/Video/test_quarantine:/repo_quarantine:rw
      - /Users/jspodick/Documents/Video/test_show:/repo_show:rw
      - ./config:/config:rw