services:
  media:
    build: .
    ports:
      - "8008:8008"
    environment:
      REPO_DIR: /repo
      SHOW_MEDIA_DIR: /repo_show
      QUARANTINE_DIR: /repo_quarantine
      CONFIG_DIR: /config
      GOOGLE_SERVICE_ACCOUNT_JSON: /config/google-service-account.json
      GOOGLE_SHEET_NAME: FileReporter2-Test
    volumes:
      - "/Volumes/media2/2H25/ContentDownload:/repo:rw"
      - "/Volumes/media2/2H25/show_media:/repo_show:rw"
      - "/Volumes/media2/2H25/quar:/repo_quarantine:rw"
      - "./config:/config:rw"
