
services:
  media:
    build: .
    ports:
      - "8008:8008"
    environment:
      REPO_DIR: /repo
      SHOW_MEDIA_DIR: /repo_show
      QUARANTINE_DIR: /repo_quarantine
      CONFIG_DIR: /config
      GOOGLE_SERVICE_ACCOUNT_JSON: /config/google-service-account.json
      GOOGLE_SHEET_NAME: FileReporter2-Test
    volumes:
      - "D:/ContentDownload/Content_Repo:/repo:rw"
      - "D:/ContentDownload/ShowFolder:/repo_show:rw"
      - "D:/ContentDownload/Quarantine:/repo_quarantine:rw"
      - "./config:/config:rw"
